"""added schema and indexes

Revision ID: aa868e0f7cab
Revises: 68c79b14d5ed
Create Date: 2024-12-04 19:52:59.175530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa868e0f7cab'
down_revision: Union[str, None] = '68c79b14d5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('required_age', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dlc_count', sa.Integer(), nullable=True),
    sa.Column('about_the_game', sa.String(), nullable=True),
    sa.Column('supported_languages', sa.String(), nullable=True),
    sa.Column('windows', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.Boolean(), nullable=True),
    sa.Column('linux', sa.Boolean(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('score_rank', sa.Integer(), nullable=True),
    sa.Column('developers', sa.String(), nullable=True),
    sa.Column('publishers', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csv_data_appid', 'csv_data', ['appid'], unique=False)
    op.create_index('ix_csv_data_appid_name', 'csv_data', ['appid', 'name'], unique=False)
    op.create_index('ix_csv_data_appid_name_release_date', 'csv_data', ['appid', 'name', 'release_date'], unique=False)
    op.create_index('ix_csv_data_appid_release_date', 'csv_data', ['appid', 'release_date'], unique=False)
    op.create_index('ix_csv_data_id', 'csv_data', ['id'], unique=False)
    op.create_index('ix_csv_data_name', 'csv_data', ['name'], unique=False)
    op.create_index('ix_csv_data_name_price', 'csv_data', ['name', 'price'], unique=False)
    op.create_index('ix_csv_data_name_release_date', 'csv_data', ['name', 'release_date'], unique=False)
    op.create_index('ix_csv_data_release_date', 'csv_data', ['release_date'], unique=False)
    op.create_index('ix_csv_data_release_date_price', 'csv_data', ['release_date', 'price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_csv_data_release_date_price', table_name='csv_data')
    op.drop_index('ix_csv_data_release_date', table_name='csv_data')
    op.drop_index('ix_csv_data_name_release_date', table_name='csv_data')
    op.drop_index('ix_csv_data_name_price', table_name='csv_data')
    op.drop_index('ix_csv_data_name', table_name='csv_data')
    op.drop_index('ix_csv_data_id', table_name='csv_data')
    op.drop_index('ix_csv_data_appid_release_date', table_name='csv_data')
    op.drop_index('ix_csv_data_appid_name_release_date', table_name='csv_data')
    op.drop_index('ix_csv_data_appid_name', table_name='csv_data')
    op.drop_index('ix_csv_data_appid', table_name='csv_data')
    op.drop_table('csv_data')
    # ### end Alembic commands ###
